export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCESS = "ALL_BLOG_SUCESS";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const POST_BLOG_REQUEST = "POST_BLOG_REQUEST";
export const POST_BLOG_REQUEST_SUCCESS = "POST_BLOG_REQUEST_SUCCESS";
export const POST_BLOG_REQUEST_FAIL = "POST_BLOG_REQUEST_FAIL";

export const DEL_BLOG_REQUEST = "DEL_BLOG_REQUEST";
export const DEL_BLOG_REQUEST_SUCCESS = "DEL_BLOG_REQUEST_SUCCESS";
export const DEL_BLOG_REQUEST_FAIL = "DEL_BLOG_REQUEST_FAIL";

export const EDIT_BLOG_REQUEST = "EDIT_BLOG_REQUEST";
export const EDIT_BLOG_REQUEST_SUCCESS = "EDIT_BLOG_REQUEST_SUCCESS";
export const EDIT_BLOG_REQUEST_FAIL = "EDIT_BLOG_REQUEST_FAIL";



